// All my screens are export from within this file.
export { default as Login } from './LoginScreen/Login'
export { default as SignUp } from './SignUpScreen/SignUp'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as Profile } from './Account/Profile'
export { default as Accommodation } from './Accommodations/AccView'
export { default as ListAccommodation } from './Accommodations/List_of_accommodations'
export { default as ListActivities } from './Activity/List_of_activities'
export { default as Payment } from './Payment/Pay'
export { default as SourvinerView } from './sourviners/SourvinerView'
export { default as MakeReservation } from './Accommodations/reservation'
export { default as ViewTourPackage } from './Activity/ViewActivity'
export { default as Cart } from './Cart/Cart'
export { default as Notification } from './Account/Notification'
export { default as PaymentMethod } from './Account/PaymentMethods'
export { default as Settings } from './Account/Settings'
export { default as Memory } from './Account/Memories'