export { default as Login } from './components/screens/LoginScreen/Login'
export { default as SignUp } from './components/screens/SignUpScreen/SignUp'
export { default as Dashboard } from './components/screens/Dashboard/Dashboard'
export { default as Profile } from './components/screens/Account/Profile'
export { default as Accommodation } from './components/screens/Accommodations/AccView'
export { default as ListAccommodation } from './components/screens/Accommodations/List_of_accommodations'
export { default as Payment } from './components/screens/Payment/Pay'